// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Uwp.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Genre
    {
        /// <summary>
        /// Initializes a new instance of the Genre class.
        /// </summary>
        public Genre() { }

        /// <summary>
        /// Initializes a new instance of the Genre class.
        /// </summary>
        public Genre(string libelle, int? id = default(int?), IList<Film> films = default(IList<Film>))
        {
            Id = id;
            Libelle = libelle;
            Films = films;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "libelle")]
        public string Libelle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "films")]
        public IList<Film> Films { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Libelle == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Libelle");
            }
            if (this.Films != null)
            {
                foreach (var element in this.Films)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
